<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-02-27 09:00
=======
# Generated by Django 5.1.4 on 2025-02-08 04:52
>>>>>>> b4347e1de8487fb47b221dd6fe939056af9c2ad7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreParcela', models.CharField(max_length=50)),
                ('fechaPlantacion', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
