# Generated by Django 5.1.4 on 2025-02-27 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoInforme', models.CharField(max_length=50)),
                ('fechaGeneracion', models.DateField()),
                ('idPlantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='plantaciones.plantacion')),
            ],
        ),
    ]
