# Generated by Django 5.1.4 on 2025-02-08 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guadaña', models.DateField()),
                ('necesidadArboles', models.CharField(max_length=30)),
                ('tipoTratamiento', models.CharField(max_length=30)),
                ('estadoPlantaTratamiento', models.CharField(max_length=30)),
                ('fechaAplicacionTratamiento', models.DateField()),
                ('observacionEvolucionPlanta', models.CharField(max_length=30)),
                ('fechaSeguimiento', models.DateField()),
                ('idPlantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimiento', to='plantaciones.plantacion')),
            ],
        ),
        migrations.CreateModel(
            name='Poda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPoda', models.CharField(max_length=30)),
                ('herramientasUsadas', models.CharField(max_length=60)),
                ('tecnicasUsadas', models.CharField(max_length=60)),
                ('fechaPoda', models.DateField()),
                ('idPlantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podas', to='plantaciones.plantacion')),
            ],
        ),
        migrations.CreateModel(
            name='RiegoFertilizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoRiego', models.CharField(max_length=30)),
                ('fechaRiego', models.DateField()),
                ('metodoAplicacionFertilizante', models.CharField(max_length=30)),
                ('tipoFertilizante', models.CharField(max_length=30)),
                ('nombreFertilizante', models.CharField(max_length=30)),
                ('cantidadFertilizante', models.FloatField()),
                ('medidaFertilizante', models.CharField(max_length=20)),
                ('fechaFertilizante', models.DateField()),
                ('idPlantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riego_fertilizacion', to='plantaciones.plantacion')),
            ],
        ),
    ]
