# Generated by Django 5.1.4 on 2025-03-05 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guadana', models.DateField(blank=True, null=True)),
                ('necesidadArboles', models.CharField(blank=True, max_length=30, null=True)),
                ('tipoTratamiento', models.CharField(blank=True, choices=[('insecticida', 'Insecticida'), ('fungicida', 'Fungicida'), ('herbicida', 'Herbicida')], max_length=30, null=True)),
                ('fechaAplicacionTratamiento', models.DateField(blank=True, null=True)),
                ('idPlantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimiento', to='plantaciones.plantacion')),
            ],
        ),
        migrations.CreateModel(
            name='Poda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPoda', models.CharField(blank=True, choices=[('formacion', 'Formación'), ('mantenimiento', 'Mantenimiento'), ('sanitaria', 'Sanitaria')], max_length=30, null=True)),
                ('herramientasUsadas', models.CharField(blank=True, choices=[('tijeras', 'Tijeras'), ('serrucho', 'Serrucho'), ('motosierra', 'Motosierra')], max_length=60, null=True)),
                ('tecnicasUsadas', models.CharField(blank=True, choices=[('ralo', 'Raleo'), ('deschuponado', 'Deschuponado'), ('rebaje', 'Rebaje')], max_length=60, null=True)),
                ('fechaPoda', models.DateField(blank=True, null=True)),
                ('idPlantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podas', to='plantaciones.plantacion')),
            ],
        ),
        migrations.CreateModel(
            name='RiegoFertilizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoRiego', models.CharField(blank=True, choices=[('aspersión', 'Aspersión'), ('goteo', 'Goteo'), ('gravedad', 'Gravedad')], max_length=30, null=True)),
                ('fechaRiego', models.DateField(blank=True, null=True)),
                ('metodoAplicacionFertilizante', models.CharField(blank=True, choices=[('al suelo', 'Al suelo'), ('foliar', 'Foliar'), ('fertirriego', 'Fertirriego')], max_length=30, null=True)),
                ('tipoFertilizante', models.CharField(blank=True, choices=[('orgánico', 'Orgánico'), ('químico', 'Químico'), ('mixto', 'Mixto')], max_length=30, null=True)),
                ('nombreFertilizante', models.CharField(blank=True, max_length=30, null=True)),
                ('cantidadFertilizante', models.FloatField(blank=True, null=True)),
                ('medidaFertilizante', models.CharField(blank=True, choices=[('kg', 'Kilogramos'), ('litros', 'Litros'), ('toneladas', 'Toneladas')], max_length=20, null=True)),
                ('fechaFertilizante', models.DateField(blank=True, null=True)),
                ('idPlantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riego_fertilizacion', to='plantaciones.plantacion')),
            ],
        ),
    ]
