# Generated by Django 5.1.4 on 2025-02-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimientomonitoreo',
            name='estadoPlantaTratamiento',
        ),
        migrations.RemoveField(
            model_name='mantenimientomonitoreo',
            name='fechaSeguimiento',
        ),
        migrations.RemoveField(
            model_name='mantenimientomonitoreo',
            name='observacionEvolucionPlanta',
        ),
        migrations.AlterField(
            model_name='mantenimientomonitoreo',
            name='fechaAplicacionTratamiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimientomonitoreo',
            name='guadaña',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimientomonitoreo',
            name='necesidadArboles',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimientomonitoreo',
            name='tipoTratamiento',
            field=models.CharField(blank=True, choices=[('insecticida', 'Insecticida'), ('fungicida', 'Fungicida'), ('herbicida', 'Herbicida')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='poda',
            name='fechaPoda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poda',
            name='herramientasUsadas',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='poda',
            name='tecnicasUsadas',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='poda',
            name='tipoPoda',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='riegofertilizacion',
            name='cantidadFertilizante',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riegofertilizacion',
            name='fechaFertilizante',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riegofertilizacion',
            name='fechaRiego',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riegofertilizacion',
            name='medidaFertilizante',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='riegofertilizacion',
            name='metodoAplicacionFertilizante',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='riegofertilizacion',
            name='nombreFertilizante',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='riegofertilizacion',
            name='tipoFertilizante',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='riegofertilizacion',
            name='tipoRiego',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
