# Generated by Django 5.1.4 on 2025-02-21 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_remove_mantenimientomonitoreo_estadoplantatratamiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimientomonitoreo',
            old_name='guadaña',
            new_name='guadana',
        ),
    ]
