# Generated by Django 5.1.4 on 2025-03-05 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCosecha', models.DateField(auto_now_add=True)),
                ('cantidadAltaCalidad', models.FloatField()),
                ('cantidadMedianaCalidad', models.FloatField()),
                ('cantidadBajaCalidad', models.FloatField()),
                ('idPlantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='plantaciones.plantacion')),
            ],
        ),
    ]
