<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-02-27 09:00
=======
# Generated by Django 5.1.4 on 2025-02-08 04:52
>>>>>>> b4347e1de8487fb47b221dd6fe939056af9c2ad7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('fechaCosecha', models.DateField(auto_now_add=True)),
                ('cantidadAltaCalidad', models.FloatField()),
                ('cantidadMedianaCalidad', models.FloatField()),
                ('cantidadBajaCalidad', models.FloatField()),
                ('idPlantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='plantaciones.plantacion')),
            ],
        ),
=======
                ('cantidadCosechada', models.FloatField()),
                ('calidadMediaCosechada', models.CharField(max_length=60)),
                ('fechaCosecha', models.DateField()),
                ('idPlantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='plantaciones.plantacion')),
            ],
        ),
        migrations.CreateModel(
            name='PostCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadMenos150', models.IntegerField()),
                ('cantidadMenos250', models.IntegerField()),
                ('cantidadMayor250', models.IntegerField()),
                ('idPlantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_cosecha', to='plantaciones.plantacion')),
            ],
        ),
>>>>>>> b4347e1de8487fb47b221dd6fe939056af9c2ad7
    ]
