# Generated by Django 5.1.4 on 2025-02-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosecha',
            name='calidadMediaCosechada',
        ),
        migrations.AddField(
            model_name='cosecha',
            name='kilosCalidadExportacion',
            field=models.FloatField(blank=True, null=True, verbose_name='Kilos de calidad exportación'),
        ),
        migrations.AddField(
            model_name='cosecha',
            name='kilosCalidadIndustrial',
            field=models.FloatField(blank=True, null=True, verbose_name='Kilos de calidad industrial'),
        ),
        migrations.AddField(
            model_name='cosecha',
            name='kilosCalidadNacional',
            field=models.FloatField(blank=True, null=True, verbose_name='Kilos de calidad nacional'),
        ),
        migrations.DeleteModel(
            name='PostCosecha',
        ),
    ]
