# Generated by Django 5.1.4 on 2025-03-05 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparacionTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limpiezaTerreno', models.DateField(blank=True, null=True)),
                ('analisisSuelo', models.DateField(blank=True, null=True)),
                ('correcionSuelo', models.DateField(blank=True, null=True)),
                ('labranza', models.DateField(blank=True, null=True)),
                ('delimitacionParcela', models.FloatField(default=0)),
                ('idPlantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparaciones', to='plantaciones.plantacion')),
            ],
        ),
        migrations.CreateModel(
            name='SeleccionArboles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccionVariedades', models.CharField(choices=[('aguacate hass', 'Aguacate Hass'), ('aguacate criollo', 'Aguacate Criollo'), ('aguacate papelillo', 'Aguacate Papelillo')], max_length=50)),
                ('preparacionColinos', models.DateField(blank=True, default=None, null=True)),
                ('excavacionHoyos', models.DateField(blank=True, null=True)),
                ('plantacion', models.DateField(blank=True, null=True)),
                ('idPlantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seleccion_arboles', to='plantaciones.plantacion')),
            ],
        ),
    ]
