# Generated by Django 5.1.4 on 2025-02-08 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparacionTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limpiezaTerreno', models.DateField()),
                ('analisisSuelo', models.DateField()),
                ('correcionSuelo', models.DateField()),
                ('labranza', models.DateField()),
                ('delimitacionParcela', models.FloatField()),
                ('idPlantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparaciones', to='plantaciones.plantacion')),
            ],
        ),
        migrations.CreateModel(
            name='SeleccionArboles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccionVariedades', models.CharField(max_length=30)),
                ('preparacionColinos', models.DateField()),
                ('excavacionHoyos', models.DateField()),
                ('plantacion', models.DateField()),
                ('idPlantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seleccion_arboles', to='plantaciones.plantacion')),
            ],
        ),
    ]
