# Generated by Django 5.1.4 on 2025-02-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparacionterreno',
            name='analisisSuelo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preparacionterreno',
            name='correcionSuelo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preparacionterreno',
            name='delimitacionParcela',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='preparacionterreno',
            name='labranza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preparacionterreno',
            name='limpiezaTerreno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seleccionarboles',
            name='excavacionHoyos',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seleccionarboles',
            name='plantacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seleccionarboles',
            name='preparacionColinos',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seleccionarboles',
            name='seleccionVariedades',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
