# Generated by Django 5.1.4 on 2025-02-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0002_alter_preparacionterreno_analisissuelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleccionarboles',
            name='seleccionVariedades',
            field=models.CharField(choices=[('aguacate hass', 'Aguacate Hass'), ('aguacate criollo', 'Aguacate Criollo'), ('aguacate papelillo', 'Aguacate Papelillo')], max_length=50),
        ),
    ]
